<?php
require_once substr(__FILE__, 0, strlen(__FILE__) - strlen("/core.php")) . "/config.php";
require_once SCRDIR . "/febi/load.php";
$content='';
if (DBUSER) {
	$db = new Db(DBSERVER,DBUSER,DBPASS,DBNAME);
    if (!$db) {
        $content .=$db->connect_error;
        exit;
    }
}

if (file_exists(SCRDIR . dirname($_SERVER['PHP_SELF']) . '/init.php'))
    require_once SCRDIR . dirname($_SERVER['PHP_SELF']) . "/init.php";
elseif (file_exists(SCRDIR . '/init.php'))
    require_once SCRDIR . "/init.php";
else {
    session_set_cookie_params(0, "/");
    session_start();
}
if (is_file(SCRDIR . $_SERVER['PHP_SELF'])) {
    ob_start();
    require SCRDIR . $_SERVER['PHP_SELF'];
    $content .= ob_get_clean();
}
else
    $content .= "Error: ".SCRDIR . $_SERVER['PHP_SELF']." file not found!";
$febi->makeRedirect();
$febi->showheaders();
if (GZIP === true && Main::$gzip === true)
    $compress->start_compress();
$febi->showcontent($content);
if (Main::$showcopyright === true)
    echo "\n<!-- Generated by sizeofint framework (c) http://sizeofint.com 2013 -->\n<!-- Coded By George Imerlishvili (Phoebus) -->";
if (DBUSER)
    $db->disconnect();
if (GZIP === true && Main::$gzip === true)
    $compress->compress_end();
exit;
?>